In [3]:
import os
from tqdm import tqdm
import pandas as pd

In [4]:
s = list(set([i for i in os.listdir() if i[-3:] == 'csv']))
s

['2017-07-31_Seat_Leon_RT_KA_Normal.csv',
 '2017-08-02_Seat_Leon_RT_S_Normal.csv',
 '2017-07-28_Seat_Leon_KA_KA_Normal.csv',
 '2018-02-16_Seat_Leon_S_RT_Normal.csv',
 '2017-07-11_Seat_Leon_S_RT_Frei.csv',
 '2017-07-11_Seat_Leon_KA_KA_Stau.csv',
 '2018-04-23_Seat_Leon_RT_KA_Normal.csv',
 '2018-02-20_Seat_Leon_KA_KA_Frei.csv',
 '2017-07-05_Seat_Leon_S_KA_Normal.csv',
 '2018-03-19_Seat_Leon_KA_KA_Frei.csv',
 '2017-07-10_Seat_Leon_KA_KA_Stau.csv',
 '2017-07-26_Seat_Leon_S_KA_Normal.csv',
 '2017-07-31_Seat_Leon_KA_KA_Frei.csv',
 '2017-07-07_Seat_Leon_S_RT_Normal.csv',
 '2018-02-22_Seat_Leon_RT_S_Normal.csv',
 '2018-03-22_Seat_Leon_S_RT_Normal.csv',
 '2018-03-01_Seat_Leon_RT_S_Normal.csv',
 '2017-08-07_Seat_Leon_KA_RT_Frei.csv',
 '2017-07-05_Seat_Leon_RT_S_Stau.csv',
 '2018-03-02_Seat_Leon_RT_S_Normal.csv',
 '2018-02-23_Seat_Leon_S_RT_Normal.csv',
 '2018-04-23_Seat_Leon_KA_KA_Frei.csv',
 '2017-07-27_Seat_Leon_KA_KA_2_Normal.csv',
 '2018-02-23_Seat_Leon_RT_RT_Frei_Beschleunigung.csv',
 '2018-02-17_Seat_Leon_RT_BB_Frei.csv',
 '2018-02-21_Seat_Leon_KA_BB_Normal.csv',
 '2017-07-12_Seat_Leon_RT_S_Normal.csv',
 '2017-08-01_Seat_Leon_KA_KA_Frei.csv',
 '2018-03-26_Seat_Leon_RT_S_Normal.csv',
 '2017-07-28_Seat_Leon_KA_RT_Stau.csv',
 '2017-07-11_Seat_Leon_KA_S_Normal.csv',
 '2018-02-18_Seat_Leon_RT_KA_Stau.csv',
 '2017-08-08_Seat_Leon_S_RT_Normal.csv',
 '2017-07-06_Seat_Leon_KA_RT_Normal.csv',
 '2018-02-23_Seat_Leon_RT_S_Normal.csv',
 '2018-02-26_Seat_Leon_RT_KA_Normal.csv',
 '2017-08-04_Seat_Leon_S_RT_Normal.csv',
 '2018-02-21_Seat_Leon_KA_KA_Normal.csv',
 '2018-02-14_Seat_Leon_S_RT_Normal.csv',
 '2018-02-27_Seat_Leon_KA_RT_Normal.csv',
 '2018-03-29_Seat_Leon_KA_RT_Stau.csv',
 '2018-03-07_Seat_Leon_S_RT_Normal.csv',
 '2018-03-21_Seat_Leon_KA_RT_Normal.csv',
 '2017-07-07_Seat_Leon_RT_S_Normal.csv',
 '2017-08-09_Seat_Leon_RT_S_Normal.csv',
 '2017-07-12_Seat_Leon_S_RT_Normal.csv',
 '2017-08-07_Seat_Leon_RT_KA_Frei_Vollbremsung.csv',
 '2018-03-22_Seat_Leon_RT_S_Normal.csv',
 '2018-03-23_Seat_Leon_S_RT_Stau.csv',
 '2018-03-19_Seat_Leon_RT_KA_Normal.csv',
 '2017-07-26_Seat_Leon_RT_S_Stau.csv',
 '2018-02-14_Seat_Leon_RT_S_Normal.csv',
 '2017-08-05_Seat_Leon_S_CW_Normal.csv',
 '2018-02-28_Seat_Leon_RT_S_Normal.csv',
 '2018-03-06_Seat_Leon_KA_RT_Normal.csv',
 '2017-07-24_Seat_Leon_RT_KA_Normal.csv',
 '2018-03-23_Seat_Leon_RT_S_Normal.csv',
 '2017-07-14_Seat_Leon_KA_RT_Normal.csv',
 '2017-08-10_Seat_Leon_S_RT_Frei.csv',
 '2017-08-01_Seat_Leon_KA_RT_Normal.csv',
 '2018-03-20_Seat_Leon_KA_KA_Normal.csv',
 '2017-08-10_Seat_Leon_RT_S_Normal.csv',
 '2018-02-26_Seat_Leon_RT_RT_Frei.csv',
 '2018-02-26_Seat_Leon_KA_KA_Frei.csv',
 '2018-03-01_Seat_Leon_S_RT_Normal.csv',
 '2018-02-17_Seat_Leon_BB_RT_Normal_Glatteis.csv',
 '2018-03-07_Seat_Leon_RT_S_Normal.csv',
 '2018-03-08_Seat_Leon_RT_S_Normal.csv',
 '2017-08-03_Seat_Leon_S_RT_Normal.csv',
 '2017-07-27_Seat_Leon_KA_KA_Normal.csv',
 '2017-08-09_Seat_Leon_S_RT_Normal.csv',
 '2017-07-14_Seat_Leon_KA_KA_Frei.csv',
 '2017-07-06_Seat_Leon_KA_KA_Normal.csv',
 '2017-07-13_Seat_Leon_RT_KA_Stau_Messfehler.csv',
 '2018-02-28_Seat_Leon_S_RT_Normal.csv',
 '2017-07-13_Seat_Leon_KA_KA_Normal.csv',
 '2018-02-23_Seat_Leon_S_S_Stau.csv',
 '2018-02-21_Seat_Leon_BB_RT_Normal.csv',
 '2018-03-26_Seat_Leon_S_RT_Stau.csv',
 '2018-02-27_Seat_Leon_KA_KA_Normal.csv',
 '2017-08-08_Seat_Leon_RT_S_Normal.csv']

In [5]:
datas = []

for file in tqdm(s):
    data = pd.read_csv(file)
    datas.append(data)
    
pd.concat(datas , axis = 0)

100%|██████████████████████████████████████████████████████████████████████████████████| 81/81 [00:12<00:00,  6.45it/s]

,Time,Engine Coolant Temperature [Â°C],Intake Manifold Absolute Pressure [kPa],Engine RPM [RPM],Vehicle Speed Sensor [km/h],Intake Air Temperature [Â°C],Air Flow Rate from Mass Flow Sensor [g/s],Absolute Throttle Position [%],Ambient Air Temperature [Â°C],Accelerator Pedal Position D [%],Accelerator Pedal Position E [%],Engine Coolant Temperature [°C],Intake Air Temperature [°C],Ambient Air Temperature [°C]
0,07:28:41.017,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,07:28:41.107,25.0,98.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,07:28:41.168,25.0,98.0,869.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,07:28:41.258,25.0,98.0,869.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,07:28:41.348,25.0,98.0,869.0,0.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24530,08:23:28.833,91.0,100.0,772.0,0.0,27.0,0.0,13.7,19.0,14.1,14.5,NaN,NaN,NaN
24531,08:23:28.954,91.0,36.0,772.0,0.0,27.0,0.0,13.7,19.0,14.1,14.5,NaN,NaN,NaN
24532,08:23:29.075,91.0,36.0,186.0,0.0,27.0,0.0,13.7,19.0,14.1,14.5,NaN,NaN,NaN
24533,08:23:29.164,91.0,36.0,186.0,0.0,27.0,0.0,13.7,19.0,14.1,14.5,NaN,NaN,NaN
24534,08:23:29.284,91.0,36.0,186.0,0.0,92.0,0.0,13.7,19.0,14.1,14.5,NaN,NaN,NaN

In [20]:
import re

from_to_values = []

for file_name in s:
    # Use regular expression to extract 'from' and 'to' values
    match = re.search(r'(\d{4}-\d{2}-\d{2})_[^_]+_[^_]+_(\w+)_(\w+)_', file_name)
    
    if match:
        from_value = match.group(2)
        to_value = match.group(3)
        from_to_values.append((from_value, to_value))

print(from_to_values)

[('RT', 'S'), ('S', 'RT'), ('S', 'RT'), ('S', 'S'), ('KA', 'KA'), ('RT', 'S'), ('RT', 'S'), ('S', 'KA'), ('RT', 'S'), ('RT', 'KA'), ('KA', 'KA'), ('S', 'RT'), ('RT', 'KA'), ('RT', 'S'), ('RT', 'S'), ('RT', 'KA'), ('RT', 'S'), ('S', 'RT'), ('KA', 'KA'), ('KA', 'KA'), ('KA', 'KA'), ('KA', 'RT'), ('KA_KA', '2'), ('RT', 'KA'), ('S', 'RT'), ('S', 'RT'), ('S', 'RT'), ('KA', 'RT'), ('S', 'RT'), ('KA', 'KA'), ('S', 'KA'), ('RT', 'S'), ('S', 'RT'), ('BB', 'RT'), ('RT', 'RT'), ('KA', 'RT'), ('RT', 'S'), ('RT_RT', 'Frei'), ('S', 'RT'), ('KA', 'KA'), ('RT', 'S'), ('KA', 'S'), ('KA', 'KA'), ('S', 'RT'), ('KA', 'KA'), ('KA', 'BB'), ('RT_KA', 'Stau'), ('RT', 'S'), ('KA', 'RT'), ('RT', 'KA'), ('KA', 'KA'), ('KA', 'KA'), ('RT', 'S'), ('S', 'CW'), ('S', 'RT'), ('S', 'RT'), ('RT', 'S'), ('KA', 'RT'), ('RT', 'BB'), ('RT', 'S'), ('KA', 'KA'), ('KA', 'KA'), ('KA', 'RT'), ('KA', 'RT'), ('RT', 'S'), ('S', 'RT'), ('S', 'RT'), ('KA', 'KA'), ('KA', 'RT'), ('RT', 'S'), ('S', 'RT'), ('BB_RT', 'Normal'), ('RT', 'KA'), ('RT', 'S'), ('KA', 'KA'), ('KA', 'KA'), ('RT', 'S'), ('S', 'RT'), ('RT_KA', 'Frei'), ('RT', 'S'), ('KA', 'RT')]

In [21]:
unique_values = []

for i in from_to_values:
    unique_values.append(i[0])
    unique_values.append(i[1])
    

set(unique_values)

{'2',
 'BB',
 'BB_RT',
 'CW',
 'Frei',
 'KA',
 'KA_KA',
 'Normal',
 'RT',
 'RT_KA',
 'RT_RT',
 'S',
 'Stau'}